// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHOohCiPtAMq0WUf3xfpOEqlqXLTmHCY',
    appId: '1:863105917746:web:da5d2eb3ac838f1fd9ad2b',
    messagingSenderId: '863105917746',
    projectId: 'koko-and-me',
    authDomain: 'koko-and-me.firebaseapp.com',
    storageBucket: 'koko-and-me.firebasestorage.app',
    measurementId: 'G-W6PM3KR2VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXVmq4xRRrgL0MAXAa64p82KrRtLu22Q',
    appId: '1:863105917746:android:ae6ee6b17cc8385ad9ad2b',
    messagingSenderId: '863105917746',
    projectId: 'koko-and-me',
    storageBucket: 'koko-and-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQnZzsoVc-GXr75W_4esySWMOOkLMHsg',
    appId: '1:863105917746:ios:6651d90c76b0430fd9ad2b',
    messagingSenderId: '863105917746',
    projectId: 'koko-and-me',
    storageBucket: 'koko-and-me.firebasestorage.app',
    androidClientId: '863105917746-bskiqfai6gt962nv40o2dhh7aqrc3bbu.apps.googleusercontent.com',
    iosClientId: '863105917746-g5j1m96kk07qd3crru2ei9641iheeol2.apps.googleusercontent.com',
    iosBundleId: 'com.kokome.kokoAndMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQnZzsoVc-GXr75W_4esySWMOOkLMHsg',
    appId: '1:863105917746:ios:6651d90c76b0430fd9ad2b',
    messagingSenderId: '863105917746',
    projectId: 'koko-and-me',
    storageBucket: 'koko-and-me.firebasestorage.app',
    androidClientId: '863105917746-bskiqfai6gt962nv40o2dhh7aqrc3bbu.apps.googleusercontent.com',
    iosClientId: '863105917746-g5j1m96kk07qd3crru2ei9641iheeol2.apps.googleusercontent.com',
    iosBundleId: 'com.kokome.kokoAndMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrHOohCiPtAMq0WUf3xfpOEqlqXLTmHCY',
    appId: '1:863105917746:web:d523e2051f3ec5e6d9ad2b',
    messagingSenderId: '863105917746',
    projectId: 'koko-and-me',
    authDomain: 'koko-and-me.firebaseapp.com',
    storageBucket: 'koko-and-me.firebasestorage.app',
    measurementId: 'G-GBCN17783N',
  );
}
